# Generated by Django 4.0.4 on 2022-05-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='question',
        ),
        migrations.AddField(
            model_name='quizz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.quizzquestion'),
        ),
    ]
